name: Hipercistem SS

on: MIAMI ROSD BELLES FLORIDA 

jobs: MAIN SITE
  build: UP 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
Action-Conodi Riodriguez I
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
